const propiedades = [
  {
    Codigo: "TA1",
    Nombre: '"Terreno en alquiler, Talanga "',
    Documento: "TA1.pdf si",
    UbicacionEscrita:
      "Ubicado en la zona comercial donde acaban de terminar de hacer los cuatro carriles en Talanga .",
    PrecioDolares: "$607.78",
    PrecioLempiras: '"L15,000.00"',
    UbicacionGoogle: "Talanga - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Alquiler",
    Latitud: "14.42347131",
    Longitud: "-87.08391788",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "354.47",
    Metros2: "246.15",
    "Precio por Vara $": "$1.71",
    "Precio por Vara L.": "L42.32",
    "Precio por Metro $.": "$354.47",
    "Precio por Metros L.": "L60.94",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "TA1",
    Planos: "",
    "Enlace quierocasa.hn": ": Detalles de la propiedad (quierocasa.hn)",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-san-jose-de-soroguara/25526405",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en Talanga, Francisco Morazan for L15,000 | U1743304 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7358303327562574/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C1tHG0BOd2q/?img_index=1",
    WebAloha: "Se alquila terreno en Talanga – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/Alohahome.hn/posts/pfbid029k3jfcKGrg2C6gcfMpx4FtBB67w37tC8Tt7V4cq9kqbjLyF7W2fxX9STP1pQrG6Nl",
    EnlaceYoutube: "pendiente",
    EnlaceLinkedln: "pendiente",
    Adicional: "",
  },
  {
    Codigo: "T9",
    Nombre: "Terreno frente a playa Puerto Cortes",
    Documento: "T9.pdf no",
    UbicacionEscrita: "Puerto Cortes",
    PrecioDolares: '"$393,030.79"',
    PrecioLempiras: '"L9,700,000.00"',
    UbicacionGoogle: "https://maps.app.goo.gl/eth3kxj3eYFEspYj9",
    Ciudad: "Puerto Cortes",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.86601269",
    Longitud: "-87.93311123",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "3236",
    Metros2: "2705.0",
    "Precio por Vara $": "$121.46",
    "Precio por Vara L.": '"L2,997.53"',
    "Precio por Metro $.": '"$3,236.00"',
    "Precio por Metros L.": '"L3,585.97"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T9",
    Planos: "",
    "Enlace quierocasa.hn": ": Detalles de la propiedad (quierocasa.hn)",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-frente-a-playa-puerto-cortes/25520391",
    EnlaceFazWaz:
      '"Terrenos (Parcelas) en Venta en Puerto Cortes, Cortes - Anuncios (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7212015508892048/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C15uXCOOTOv/",
    WebAloha:
      '"Terreno frente a playa, Puerto Cortes – Real Estate (alohasaas.online)"',
    EnlaceTikTok:
      "https://www.tiktok.com/@alohahome.hn/video/7322282171027246382?is_from_webapp=1&sender_device=pc&web_id=7309328079892530694",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/1145873859908846/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T8",
    Nombre: "Terreno barrio independencia",
    Documento: "T8.pdf no",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$149,918.96"',
    PrecioLempiras: '"L3,700,000.00"',
    UbicacionGoogle: '"15°46\'41.0""N 86°47\'38.0""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.77832396",
    Longitud: "-86.79391009",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Victor Manuel Pineda",
    TelefonoPropietario: "9977-1917",
    Varas2: "425",
    Metros2: "297.1",
    "Precio por Vara $": "$352.75",
    "Precio por Vara L.": '"L8,705.88"',
    "Precio por Metro $.": "$425.00",
    "Precio por Metros L.": '"L12,453.72"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T8",
    Planos: "",
    "Enlace quierocasa.hn": ": Detalles de la propiedad (quierocasa.hn)",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-barrio-independencia/25520411",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L3,700,000 | U1743310 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/24573919558920777/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C2OB4ESOWRh/",
    WebAloha:
      "https://alohasaas.online/property/terreno-en-barrio-independencia-2/",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/947962263674327/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T7",
    Nombre: "10 Manzanas a 695 la vara en la Ceiba",
    Documento: "T7.pdf si",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$2,816,045.38"',
    PrecioLempiras: '"L69,500,000.00"',
    UbicacionGoogle: '"15°45\'18.8""N 86°49\'47.5""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.75543904",
    Longitud: "-86.82987183",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Juan Garcia Ponce",
    TelefonoPropietario: "9600-3676",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T7",
    Planos: "",
    "Enlace quierocasa.hn": ": Detalles de la propiedad (quierocasa.hn)",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-de-10-manzanas-en-la-ceiba/25520443",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L69,500,000 | U1743314 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/24035160372798853/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C2Wfr4sOOb3/",
    WebAloha: "10 Manzanas en La Ceiba – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/2315898532134405/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T6",
    Nombre: "Terreno en valle de angeles",
    Documento: "T6",
    UbicacionEscrita: "Valle de angeles",
    PrecioDolares: '"$151,944.89"',
    PrecioLempiras: '"L3,750,000.00"',
    UbicacionGoogle: "Valle de angeles - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.0787237",
    Longitud: "-87.16391629",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "3000",
    Metros2: "2743.2",
    "Precio por Vara $": "$50.65",
    "Precio por Vara L.": '"L1,250.00"',
    "Precio por Metro $.": '"$3,000.00"',
    "Precio por Metros L.": '"L1,367.02"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T6",
    Planos: "",
    "Enlace quierocasa.hn": ": Detalles de la propiedad (quierocasa.hn)",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-valle-de-angeles/25520466",
    EnlaceFazWaz:
      '"Terrenos (Parcelas) en Venta en Valle De Angeles, Francisco Morazan - Anuncios (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/6860302867403555/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C2WhoZpu19-/?img_index=1",
    WebAloha: "Terreno en Valle de Ángeles – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/972773370931628/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T3",
    Nombre: "Terreno con casa con acceso a playa",
    Documento: "T3 pdf si",
    UbicacionEscrita: "Puerto Cortes",
    PrecioDolares: '"$1,215,559.16"',
    PrecioLempiras: '"L30,000,000.00"',
    UbicacionGoogle: "https://maps.app.goo.gl/gKKEMFxQoto3vmZb7",
    Ciudad: "Puerto Cortes",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.8193594",
    Longitud: "-87.939418",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "9267.84",
    Metros2: "7746",
    "Precio por Vara $": "$131.16",
    "Precio por Vara L.": '"L3,237.00"',
    "Precio por Metro $.": '"$9,267.84"',
    "Precio por Metros L.": '"L3,872.97"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T3",
    Planos: "",
    "Enlace quierocasa.hn": ": Detalles de la propiedad (quierocasa.hn)",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-con-casa-con-acceso-a-playa/25520514",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en Puerto Cortes, Cortes for L30,000,000 | U1743318 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7643288155705860/50494109350",
    EnlaceInstagram: "",
    WebAloha:
      '"Terreno con acceso a playa, Puerto Cortés – Bienes Raíces (alohasaas.online)"',
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/379872441467643/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T25",
    Nombre: "Terreno Aldea de el Ovejo",
    Documento: "T25  si",
    UbicacionEscrita:
      '"Aldea de El Ovejo, municipio de Lepaterique, Francisco Morazán, Honduras, C.A"',
    PrecioDolares: '"$182,333.87"',
    PrecioLempiras: '"L4,500,000.00"',
    UbicacionGoogle: "Lepaterique - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.06785737",
    Longitud: "-87.46732957",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "2",
    NBanios: "1",
    Estacionamiento: "SI",
    Amueblado: "NO",
    Fotos: "T25",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-en-aldea-el-ovejo-lepaterique-1/9dsnbkb/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-aldea-de-el-ovejo-municipio-de-lepaterique/25520562",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-distrito-central-francisco-morazan-u1743322",
    EnlaceWhatsApp: "https://wa.me/p/7571360546216481/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/CuLpdi4v_rS/",
    WebAloha:
      "Terreno en Aldea del Ovejo T25 – Inmobiliaria (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/1141707763864707/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: '"Cuenta con café variedad Lempira en producción 16 palos',
  },
  {
    Codigo: "Cítricos: naranjas de jugo y dulce",
    Nombre: "agrarias",
    Documento: "limones",
    UbicacionEscrita: 'mandarinas y limas"',
    PrecioDolares: "",
    PrecioLempiras: "",
    UbicacionGoogle: "",
    Ciudad: "",
    TipoPropiedad: "",
    Estatus: "",
    Oferta: "",
    Latitud: "",
    Longitud: "",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    EnlaceFazWaz: "",
    EnlaceWhatsApp: "",
    EnlaceInstagram: "",
    WebAloha: "",
    EnlaceTikTok: "",
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T20",
    Nombre: "Terreno para bodega",
    Documento: "T20.pdf",
    UbicacionEscrita: '"Al lado de la escuela internacional , Tegucigalpa "',
    PrecioDolares: '"$1,050,000.00"',
    PrecioLempiras: '"L25,914,000.00"',
    UbicacionGoogle: "International School - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.04429372",
    Longitud: "-87.20002372",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "3000",
    Metros2: "2507.715",
    "Precio por Vara $": "$350.00",
    "Precio por Vara L.": '"L8,638.00"',
    "Precio por Metro $.": '"$74,040.00"',
    "Precio por Metros L.": '"L10,333.71"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T20",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-para-bodega-tegucigalpa/swzugsv/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-para-bodega/25520649",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-tegucigalpa-francisco-morazan-u1743328",
    EnlaceWhatsApp: "https://wa.me/p/6125055474264454/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/Cy2XXugO-zm/",
    WebAloha: "Terreno para bodega – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/368523749292615/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T18",
    Nombre: "Terreno cercano a cascadas mall",
    Documento: "T18.pdf",
    UbicacionEscrita: "Cercano a cascadas mall",
    PrecioDolares: '"$9,300,000.00"',
    PrecioLempiras: '"L229,524,000.00"',
    UbicacionGoogle: "Cascadas Mall - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.0760736",
    Longitud: "-87.20124297",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "15500",
    Metros2: "12956.53",
    "Precio por Vara $": "$600.00",
    "Precio por Vara L.": '"L17,714.93"',
    "Precio por Metro $.": '"$15,500.00"',
    "Precio por Metros L.": '"L17,714.93"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T18",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-cercano-a-cascadas-mall-tegucigalpa/gimfj9c/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-cercano-cascadas-mall/25520704",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-tegucigalpa-francisco-morazan-u1743332",
    EnlaceWhatsApp: "https://wa.me/p/7676617119037474/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/Cy70St8u1u3/",
    WebAloha:
      "Terreno cercano a Cascadas Mall T18 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/1043242160097117/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T13",
    Nombre: "6 manzanas en Tamara",
    Documento: "T13.pdf",
    UbicacionEscrita: "Tamara",
    PrecioDolares: '"$729,335.49"',
    PrecioLempiras: '"L18,000,000.00"',
    UbicacionGoogle: "Támara - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.17057394",
    Longitud: "-87.33516689",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "60000",
    Metros2: "50154.3",
    "Precio por Vara $": "$12.16",
    "Precio por Vara L.": "L300.00",
    "Precio por Metro $.": '"$60,000.00"',
    "Precio por Metros L.": "L358.89",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T13",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-de-6-manzanas-en-tamara-tamara/24kb4r7/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/6-manzanas-en-tamara/25520788",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-tegucigalpa-francisco-morazan-u1743338",
    EnlaceWhatsApp: "https://wa.me/p/6822771747834029/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha: "6 Manzanas en Tamara T13 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/744691717725689/",
    EnlaceYoutube: "",
    EnlaceLinkedln:
      "https://es.linkedin.com/posts/aloha-home-hn_6-manzanas-en-tamara-300-lmps-por-vara-activity-7133642418947575808-XydG?utm_source=li_share&utm_content=feedcontent&utm_medium=g_dt_web&utm_campaign=copy",
    Adicional: "",
  },
  {
    Codigo: "T28",
    Nombre: "Terreno en Venta Lomas del Mayab",
    Documento: "T28.pdf",
    UbicacionEscrita: "Lomas del Mayab",
    PrecioDolares: '"$418,320.00"',
    PrecioLempiras: '"L10,332,504.00"',
    UbicacionGoogle: "Colonia Lomas del Mayab - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.09100881",
    Longitud: "-87.18663106",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "1494",
    Metros2: "1249.88",
    "Precio por Vara $": "$280.00",
    "Precio por Vara L.": '"L6,916.00"',
    "Precio por Metro $.": '"$1,494.00"',
    "Precio por Metros L.": '"L8,266.80"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T28",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-en-lomas-del-mayab-tegucigalpa/mahcfiw/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-lomas-del-mayab/25520813",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-tegucigalpa-francisco-morazan-u1743340",
    EnlaceWhatsApp: "https://wa.me/p/5543019672464371/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/Cs4dYcUPj5c/",
    WebAloha: "Terreno en Lomas del Mayab T39 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/2328752027514235/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T21",
    Nombre: "Terreno frente Aeropuerto",
    Documento: "T21.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$530,794.17"',
    PrecioLempiras: '"L13,100,000.00"',
    UbicacionGoogle: '"15°44\'58.5""N 86°50\'53.8""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.74984145",
    Longitud: "-86.84836363",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Conchita Garcia",
    TelefonoPropietario: "9991-8917",
    Varas2: "1392",
    Metros2: "1163.58",
    "Precio por Vara $": "$381.32",
    "Precio por Vara L.": '"L11,258.36"',
    "Precio por Metro $.": '"$1,392.00"',
    "Precio por Metros L.": '"L11,258.36"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T21",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-frente-aeropuerto-la-ceiba/8c69sam/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-enfrente-de-aeropuerto-de-ceiba/25520595",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-la-ceiba-atlantida-u1743326",
    EnlaceWhatsApp: "https://wa.me/p/7361121303926977/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/CykkRewuo0E/",
    WebAloha:
      "Terreno Enfrente de Aeropuerto de Ceiba – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/948124549630655/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T45",
    Nombre: "Terreno en San Jose de Soroguara",
    Documento: "T45.pdf",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: '"$202,593.19"',
    PrecioLempiras: '"L5,000,000.00"',
    UbicacionGoogle: "Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Alquiler",
    Latitud: "14.17762309",
    Longitud: "-87.27540087",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "1148.85",
    Metros2: "958.94",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T45",
    Planos: "Plano T45",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/se-vende-o-alquila-terreno-en-san-jose-de-soroguara-tegucigalpa/ml5gg7p/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-san-jose-de-soroguara/25526405",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-distrito-central-francisco-morazan-u1743362",
    EnlaceWhatsApp: "https://wa.me/p/25813294758269469/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha:
      "Terreno en San Jose de Soroguara – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/25637299609188673/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "pendiente",
    Adicional: "",
  },
  {
    Codigo: "T2",
    Nombre: "10 Manzanas frente al mar en la ceiba",
    Documento: "T2.pdf",
    UbicacionEscrita: '"Sector de Coco Pando, con acceso a la calle 8. "',
    PrecioDolares: '"$193,800.00"',
    PrecioLempiras: '"L4,782,984.00"',
    UbicacionGoogle: '"15°46\'31.0""N 86°46\'07.9""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.77550494",
    Longitud: "-86.76880746",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "German Quiñonez",
    TelefonoPropietario: "9956-0558",
    Varas2: "193.8",
    Metros2: "162",
    "Precio por Vara $": "$70.00",
    "Precio por Vara L.": '"L1,727.60"',
    "Precio por Metro $.": '"$2,768.57"',
    "Precio por Metros L.": '"L29,524.59"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T2",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-de-10-manzanas-frente-al-mar-la-ceiba/deze5np/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-de-10-manzanas-frente-al-mar/25520680",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-la-ceiba-atlantida-u1743330",
    EnlaceWhatsApp: "https://wa.me/p/7520572474655989/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C2syn8hOBqi/",
    WebAloha:
      "10 Manzanas frente al mar en la Ceiba – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/936344474744213/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T46",
    Nombre: "Terreno en valle de angeles",
    Documento: "T46.pdf",
    UbicacionEscrita: '"Valle de Angeles Aldea las Cabañas, el mirador"',
    PrecioDolares: '"$166,733.75"',
    PrecioLempiras: '"L4,114,989.00"',
    UbicacionGoogle: "Valle de Ángeles - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.15375419",
    Longitud: "-87.03003082",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "3048.14",
    Metros2: "2125.24",
    "Precio por Vara $": "$54.70",
    "Precio por Vara L.": '"L1,350.00"',
    "Precio por Metro $.": '"$3,048.14"',
    "Precio por Metros L.": '"L1,936.25"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T46",
    Planos: "Planos T46",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-en-valle-de-angeles-valle-de-angeles/lf6nta2/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-valle-de-angeles/25520466",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-valle-de-angeles-francisco-morazan-u1743316",
    EnlaceWhatsApp: "https://wa.me/p/6886187721504317/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha: "Terreno en Valle de Ángeles – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook: "pendiente",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T17",
    Nombre: "Terreno Ceiba HN",
    Documento: "T17.pdf",
    UbicacionEscrita: '"La Ceiba, en el Naranjal"',
    PrecioDolares: '"$215,194.49"',
    PrecioLempiras: '"L5,311,000.00"',
    UbicacionGoogle: '"15°46\'52.6""N 86°47\'01.8""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.78147396",
    Longitud: "-86.78386549",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Moreira JM",
    TelefonoPropietario: "3366-3903",
    Varas2: "1305",
    Metros2: "1090.86",
    "Precio por Vara $": "$164.90",
    "Precio por Vara L.": '"L4,868.65"',
    "Precio por Metro $.": '"$1,305.00"',
    "Precio por Metros L.": '"L4,868.65"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T17",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-en-la-ceiba-la-ceiba/uhz646f/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-ceiba/25520744",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-la-ceiba-atlantida-u1743334",
    EnlaceWhatsApp: "https://wa.me/p/6746371942147877/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/CzuG__zOypM/",
    WebAloha:
      "https://alohasaas.online/property/terreno-en-ceiba-en-el-naranjal/",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1601130974058168/",
    EnlaceYoutube: "",
    EnlaceLinkedln:
      "https://es.linkedin.com/posts/aloha-home-hn_se-vende-terreno-en-ceiba-1305-activity-7131085113655791616-wFQo?utm_source=li_share&utm_content=feedcontent&utm_medium=g_dt_web&utm_campaign=copy",
    Adicional: "",
  },
  {
    Codigo: "T14",
    Nombre: "Terreno en venta la ceiba hn",
    Documento: "T14.pdf",
    UbicacionEscrita: "Colonia D’Antoni",
    PrecioDolares: '"$14,586.71"',
    PrecioLempiras: '"L360,000.00"',
    UbicacionGoogle: '"15°46\'18.1""N 86°48\'35.6""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.77186992",
    Longitud: "-86.80986744",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Conchita Garcia",
    TelefonoPropietario: "9991-8917",
    Varas2: "218.72",
    Metros2: "200",
    "Precio por Vara $": "$66.69",
    "Precio por Vara L.": '"L1,645.94"',
    "Precio por Metro $.": "$218.72",
    "Precio por Metros L.": '"L1,800.00"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T14",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-en-la-ceiba-la-ceiba/g2y8mz3/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-la-ceiba/25520761",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/terreno-parcela-en-venta-en-la-ceiba-atlantida-u1743336",
    EnlaceWhatsApp: "https://wa.me/p/7395428540477902/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/Cz4FWvPOwP8/",
    WebAloha: "Terreno en Colonia D’Antoni – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1078713159870674/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T12",
    Nombre: "Terreno de 2 Manzanas en Ceiba",
    Documento: "T12.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$344,408.43"',
    PrecioLempiras: '"L8,500,000.00"',
    UbicacionGoogle: '"15°45\'13.7""N 86°50\'15.9""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.75405342",
    Longitud: "-86.83769636",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Salvador Azcona (Yolanda Azcona)",
    TelefonoPropietario: "8906-3472",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T12",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24":
      "Lotes y Terrenos La Ceiba | venta | Terreno de 2 Manzanas en Ceiba : HNL 8500000.00 (encuentra24.com)",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L8,500,000 | U1759044 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/24071004832544978/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C05kfG6uUh0/",
    WebAloha: "Terreno de 2 Manzanas en Ceiba – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/2943231635818312/",
    EnlaceYoutube: "",
    EnlaceLinkedln:
      "https://es.linkedin.com/posts/aloha-home-hn_se-venden-2-manzanas-en-ceiba-85-millones-activity-7141648904038592512-Rr03?utm_source=li_share&utm_content=feedcontent&utm_medium=g_dt_web&utm_campaign=copy",
    Adicional: "",
  },
  {
    Codigo: "ED1",
    Nombre: '"Edificio, Colonia Pizzati"',
    Documento: "ED1.pdf",
    UbicacionEscrita: '"Colonia Pizzatti en La Ciudad de la Ceiba, Atlántida."',
    PrecioDolares: '"$200,000.00"',
    PrecioLempiras: '"L4,800,000.00"',
    UbicacionGoogle: "Col Pizzaty - Google Maps",
    Ciudad: "La Ceiba",
    TipoPropiedad: "Edificio",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.77628176",
    Longitud: "-86.77365122",
    DirectaOCompartida: "Compartido",
    NCompartidos: "1",
    ContactoPropietario: "Melania (Bienes y racises SENRA)",
    TelefonoPropietario: "9738-7354",
    Varas2: "492.36",
    Metros2: "346.29",
    "Precio por Vara $": "$406.21",
    "Precio por Vara L.": '"L9,748.96"',
    "Precio por Metro $.": "$492.36",
    "Precio por Metros L.": '"L13,861.21"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "SI",
    Fotos: "ED1",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-edificio-de-apartamentos-en-la-ceiba-la-ceiba/kto83yc/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-edificios/edificio-de-apartamentos/25521426",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/10-habitaci%C3%B3n-whole-building-en-venta-en-la-ceiba-atlantida-u1743352",
    EnlaceWhatsApp: "https://wa.me/p/24549778191334261/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/C3HSl8GOoGA/",
    WebAloha: "Edificio en Colonia Pizzatti – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/1464848171097370/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "Edificio de dos niveles con 7 apartamentos",
  },
  {
    Codigo: "C6",
    Nombre: "Villa en Palma Real L6",
    Documento: "C6.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$175,000.00"',
    PrecioLempiras: '"L4,319,000.00"',
    UbicacionGoogle: '"15°47\'40.6""N 86°35\'33.8""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.79474531",
    Longitud: "-86.59277146",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Don Hugo",
    TelefonoPropietario: "1 (407) 733-5582",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "3",
    NBanios: "3",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C6",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-villa-en-palma-real-la-ceiba/58fyv7n/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-casas/villa-en-palma-real-c6/25520897",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/3-habitaci%C3%B3n-villa-en-venta-en-la-ceiba-atlantida-u1743344",
    EnlaceWhatsApp: "https://wa.me/p/6997392843705504/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/CysLtkVu757/?img_index=1",
    WebAloha: "Villa en Palma Real C6 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/374864098637942/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C5",
    Nombre: "Villa en Palma Real amueblada L13",
    Documento: "C5.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$220,268.00"',
    PrecioLempiras: '"L5,436,214.24"',
    UbicacionGoogle: '"15°47\'40.6""N 86°35\'33.9""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.7947866",
    Longitud: "-86.59275",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Don Hugo",
    TelefonoPropietario: "1 (407) 733-5582",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "3",
    NBanios: "3",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C5",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-casa-en-villa-en-palma-real-la-ceiba/pwvhahm/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-casas/villa-en-palma-real-c5/25520930",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/3-habitaci%C3%B3n-villa-en-venta-en-la-ceiba-atlantida-u1743346",
    EnlaceWhatsApp: "https://wa.me/p/6774162552687681/50494109350",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha: "Villa en Palma Real C5 – Real Estate (alohasaas.online)",
    EnlaceTikTok:
      '"(99+)🍍 (C5) Se vende villa en Palma Real 🌴 Completamente amueblada 3 hab,... | TikTok"',
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/374864098637942/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "pendiente",
    Adicional: "",
  },
  {
    Codigo: "C4",
    Nombre: "Casa Residencial El Naranjal",
    Documento: "C4.pdf",
    UbicacionEscrita: "Residencial El Naranjal",
    PrecioDolares: '"$365,475.57"',
    PrecioLempiras: '"L9,019,937.00"',
    UbicacionGoogle: '"15°47\'04.3""N 86°47\'13.6""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.78474461",
    Longitud: "-86.7871111",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Salvador Guerrero",
    TelefonoPropietario: "9484-6091 (94845516 esposa)",
    Varas2: "1912",
    Metros2: "1598.25",
    "Precio por Vara $": "$191.15",
    "Precio por Vara L.": '"L4,717.54"',
    "Precio por Metro $.": '"$1,912.00"',
    "Precio por Metros L.": '"L5,643.63"',
    NHabitaciones: "4",
    NBanios: "3",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C4",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-casa-en-residencial-el-naranjal-puerto-cort-s/biisbe8/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-casas/se-vende-o-renta-casa-en-residencial-el-naranjal/25520999",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/4-habitaci%C3%B3n-casa-en-venta-en-la-ceiba-atlantida-u1743348",
    EnlaceWhatsApp: "https://wa.me/p/25004201912529189/50494109350",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha:
      "Casa en Residencial El Naranjal – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/772213630986184/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C1",
    Nombre: "Villa en Palma Real",
    Documento: "C1.pdf",
    UbicacionEscrita: '"Palma Real, La Ceiba Atlantida "',
    PrecioDolares: '"$230,000.00"',
    PrecioLempiras: '"L5,676,400.00"',
    UbicacionGoogle: '"Villa, Palma Real - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.79514417",
    Longitud: "-86.59188866",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Luis Castillo",
    TelefonoPropietario: "99951556",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "3",
    NBanios: "2",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C1",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-casas-en-villa-palma-real-la-ceiba/6fqh3v3/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-casas/villa-en-palma-real-c1/25521030",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/3-habitaci%C3%B3n-villa-en-venta-en-la-ceiba-atlantida-u1743350",
    EnlaceWhatsApp: "https://wa.me/p/7193672767379156/50494109350",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha: "Villa en Palma Real C1 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://web.facebook.com/marketplace/item/818165073658025/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C26",
    Nombre: "Casa redisencial Genova",
    Documento: "C26.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$157,127.23"',
    PrecioLempiras: '"L3,877,900.00"',
    UbicacionGoogle: '"15°46\'31.0""N 86°46\'07.9""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.77547135",
    Longitud: "-86.76889969",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Yohana Baca",
    TelefonoPropietario: "32496721",
    Varas2: "437.69",
    Metros2: "306.31",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "3",
    NBanios: "2",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C26",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      '"Casa de 3 Habitación en Venta en La Ceiba, Atlantida for L3,877,900 | U1759042 (fazwaz.com.hn)"',
    EnlaceFazWaz:
      "(C26) Se Vende Casa Amueblada en La Ceiba | 3 Recamaras por 3877900.00 en La Ceiba (encuentra24.com)",
    EnlaceWhatsApp: "https://wa.me/p/5947979341964835/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/CqGEuCHO86M/?img_index=1",
    WebAloha: "Casa Residencial Génova C26 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook: "pendiente",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "AP21",
    Nombre: "Apartamento en renta SPS",
    Documento: "AP21.pdf",
    UbicacionEscrita: "San Pedro Sula",
    PrecioDolares: '"$1,350.00"',
    PrecioLempiras: '"L33,318.00"',
    UbicacionGoogle:
      '"https://www.google.com/maps/place/Condominios+vistas+del+merendon,+San+Pedro+Sula/@15.4994956,-88.0500669,17z/data=!3m1!4b1!4m6!3m5!1s0x8f665bdc6730a103:0x6801667e78335088!8m2!3d15.4994956!4d-88.047492!16s%2Fg%2F11tmmp95f7?entry=ttu"',
    Ciudad: "San Pedro Sula",
    TipoPropiedad: "Apartamento",
    Estatus: "Disponible",
    Oferta: "Alquiler",
    Latitud: "15.49963",
    Longitud: "-88.04752419",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "2",
    NBanios: "2",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "AP21",
    Planos: "",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/renta-de-apartamento-en-san-pedro-sula-san-pedro-sula/c56v988/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-alquiler-apartamentos/apartamento-en-sps/25525458",
    EnlaceFazWaz:
      "Apartamento de 2 Habitación en Alquiler en Vistas del Merendon for L1/mo | U1743358 (fazwaz.com.hn)",
    EnlaceWhatsApp: "https://wa.me/p/7109870232381611/50494109350",
    EnlaceInstagram: "Pendiente",
    WebAloha:
      "Apartamento en renta amueblado en San Pedro Sula – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1340358936624821/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C43",
    Nombre: "Villa en Palma Real",
    Documento: "C43.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$130,000.00"',
    PrecioLempiras: '"L3,208,400.00"',
    UbicacionGoogle:
      '"Villa, Palma Real, Honduras, Cancún a Villa, Palma Real - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.80104992",
    Longitud: "-86.59156362",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "2",
    NBanios: "2",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C43",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-casas/villa-en-palma-real-c43/25536369",
    EnlaceFazWaz:
      '"Villa de 2 Habitación en Venta en La Ceiba, Atlantida for L3,208,400 | U1744414 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/24855160064131231/50494109350",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha: "Villa en Palma Real C43 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1400966947188343/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "ED2",
    Nombre: '"Edificio, en Barrio Solares Nuevos"',
    Documento: "ED2.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$283,630.47"',
    PrecioLempiras: '"L7,000,000.00"',
    UbicacionGoogle:
      '" https://www.google.com/maps?q=15.780194282531738,-86.79120635986328&z=17&hl=es"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Edificio",
    Estatus: "Disponible",
    Oferta: "Venta/Alquiler",
    Latitud: "15.78031818",
    Longitud: "-86.79126005",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Steven",
    TelefonoPropietario: "9494-4461",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "5",
    NBanios: "5",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "ED2",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-edificios/se-vende-o-renta-edificio-edificio-de-2-pisos-de-apartamentos-y-local-comercial/25536593",
    EnlaceFazWaz:
      "https://www.fazwaz.com.hn/propiedad-e-Inmueble-venta/5-habitaci%C3%B3n-whole-building-en-venta-en-la-ceiba-atlantida-u1744418",
    EnlaceWhatsApp: "https://wa.me/p/24570021242643608/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha: "Edificio de apartamentos ED2 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1791735331324953/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "pendiente",
    Adicional:
      '"Apartamento 1  de dos habitaciones 10,000  lempiras.    3 apartamentos de 1 habitación 8,000 lempiras cada uno.                                                                                                               Local planta baja 40,000 lempiras negociable      "',
  },
  {
    Codigo: "T47",
    Nombre: "Terreno en barrio el centro",
    Documento: "T47.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$38,492.71"',
    PrecioLempiras: '"L950,000.00"',
    UbicacionGoogle: '"15°47\'18.2""N 86°47\'32.4""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.78860571",
    Longitud: "-86.79231184",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Anny - Dulce/Gustavo Maldonado",
    TelefonoPropietario: "3200-1976 - 96105144",
    Varas2: "228.35",
    Metros2: "209.02",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T47",
    Planos: "Planos T47",
    "Enlace quierocasa.hn":
      "https://www.quierocasa.hn/venta-de-terreno-en-barrio-independencia-la-ceiba/rv92kna/prd",
    "Enlace encuentra24":
      "https://www.encuentra24.com/honduras-es/bienes-raices-venta-de-propiedades-lotes-y-terrenos/terreno-en-barrio-independencia/25520411",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L950,000 | U1758090 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7025205997532519/50494109350",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha:
      '"Terreno en barrio el centro, La Ceiba – Bienes Raíces (alohasaas.online)"',
    EnlaceTikTok:
      "https://www.tiktok.com/@alohahome.hn/video/7346010730509897002?is_from_webapp=1&sender_device=pc&web_id=7309328079892530694",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/800224021948014/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "pendiente",
    Adicional: "",
  },
  {
    Codigo: "ED3",
    Nombre: "Edificio y casa Barrio Alvarado 20 Avenida 14 de julio",
    Documento: "ED3 (1).pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$648,298.22"',
    PrecioLempiras: '"L16,000,000.00"',
    UbicacionGoogle: '"15°46\'31.7""N 86°47\'07.1""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Edificio",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.77567",
    Longitud: '"-8,678,532"',
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Enrique Papp Alvarado",
    TelefonoPropietario: "9405-0746",
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "3",
    NBanios: "3",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "ED3",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      "Venta de Edificio y casa en Barrio Alvarado | 3 Recamaras por 16000.00 en La Ceiba (encuentra24.com)",
    EnlaceFazWaz:
      '"Whole Building de 3 Habitación en Venta en La Ceiba, Atlantida for L16,000,000 | U1756918 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7151049261640017/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha:
      "Edificio y Casa en Barrio Alvarado – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/382069204601072/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "pendiente",
    Adicional: "",
  },
  {
    Codigo: "T48",
    Nombre: '"Terreno a orilla de playa, se ve enfrente cayos cochinos"',
    Documento: "T48.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$300,000.00"',
    PrecioLempiras: '"L7,404,000.00"',
    UbicacionGoogle: '"15°47\'31.4""N 86°38\'59.5""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.79228429",
    Longitud: "-86.64989952",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Luis Castillo",
    TelefonoPropietario: "99951556",
    Varas2: "10343.78",
    Metros2: "8656.92",
    "Precio por Vara $": "$29.00",
    "Precio por Vara L.": "L715.79",
    "Precio por Metro $.": '"$10,343.78"',
    "Precio por Metros L.": "L855.27",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T48",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      '"Propiedades de playa La Ceiba | venta | Se vende propiedad a orilla de playa, Cayos Cochinos T48 : HNL 7404000.00 (encuentra24.com)"',
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L7,404,000 | U1756920 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7635383376514513/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha:
      '"Terreno a orilla de playa, Cayos cochinos – Bienes Raíces (alohasaas.online)"',
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/920652412942824/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "pendiente",
    Adicional: "",
  },
  {
    Codigo: "T49",
    Nombre: "Terreno 9.55 manzanas Roma La Ceiba",
    Documento: "T49.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$1,094,003.24"',
    PrecioLempiras: '"L27,000,000.00"',
    UbicacionGoogle: '"15°47\'05.2""N 86°35\'40.8""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.78499461",
    Longitud: "-86.5946667",
    DirectaOCompartida: "Compartido",
    NCompartidos: "3",
    ContactoPropietario: "(Cenra/ comisionista/Aloha",
    TelefonoPropietario: '"9738-754, 98670525"',
    Varas2: "",
    Metros2: "",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T49",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      "Lotes y Terrenos La Ceiba | venta | Venta de terreno 9.55 manzanas Roma La Ceiba : HNL 27000000.00 (encuentra24.com)",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L27,000,000 | U1756924 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/24754629870852386/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha:
      '"Terreno 9.55 Manzanas, La Ceiba – Bienes Raíces (alohasaas.online)"',
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1130478494805209/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "pendiente",
    Adicional: "",
  },
  {
    Codigo: "T50",
    Nombre: "Terreno en residencial monte real del bosque",
    Documento: "T50.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$28,363.05"',
    PrecioLempiras: '"L700,000.00"',
    UbicacionGoogle: '"15°47\'05.2""N 86°35\'40.8""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.76630391",
    Longitud: "-86.7527124",
    DirectaOCompartida: "Compartido",
    NCompartidos: "1",
    ContactoPropietario: "Adriana Herrera",
    TelefonoPropietario: "9867-0625",
    Varas2: "428.6",
    Metros2: "298.82",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T50",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      "Lotes y Terrenos La Ceiba | venta | Terreno en residencial monte real : HNL 700000.00 (encuentra24.com)",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L700,000 | U1757530 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7358184974203511/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha:
      "Terreno en residencial monte real del bosque – Bienes Raíces (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/428454169629895/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T51",
    Nombre: "Terrenos cerca del mar en la ensenada",
    Documento: "T51.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$44,570.50"',
    PrecioLempiras: '"L1,100,000.00"',
    UbicacionGoogle: '"15°47\'27.5""N 86°39\'26.2""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.79121111",
    Longitud: "-86.65728",
    DirectaOCompartida: "Directo",
    NCompartidos: "-",
    ContactoPropietario: "Luis Castillo",
    TelefonoPropietario: "99951556",
    Varas2: "393.42",
    Metros2: "275",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T51",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24":
      '"Lotes y Terrenos La Ceiba | venta | Terreno cerca del mar en la ensenada, En La Ceiba : HNL 700000.00 (encuentra24.com)"',
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en La Ceiba, Atlantida for L700,000 | U1757550 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/7384965118231353/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha:
      "Terreno cerca del mar en la ensenada – Bienes Raíces (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/2302838746587790/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C8",
    Nombre: "Casa Miramontes",
    Documento: "C8.pdf",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: '"$323,886.00"',
    PrecioLempiras: '"L8,000,000.00"',
    UbicacionGoogle: "Miramontes - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.08665131",
    Longitud: "-87.19943413",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "503.79",
    Metros2: "461.20",
    "Precio por Vara $": "$642.90",
    "Precio por Vara L.": '"L17,346.05"',
    "Precio por Metro $.": "$503.79",
    "Precio por Metros L.": '"L17,346.05"',
    NHabitaciones: "2",
    NBanios: "1",
    Estacionamiento: "SI",
    Amueblado: "NO",
    Fotos: "C8",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    EnlaceFazWaz: "",
    EnlaceWhatsApp: "https://wa.me/p/6635689593223524/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/CwlfjwnBjnr/",
    WebAloha: "Casa en Miramontes C8 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1743834992776059/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T39",
    Nombre: "Terreno lomas del Mayab",
    Documento: "T39.pdf",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: '"$418,320.00"',
    PrecioLempiras: '"L10,324,137.60"',
    UbicacionGoogle: "Colonia Lomas del Mayab - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.09140428",
    Longitud: "-87.18687781",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "1494",
    Metros2: "1249.68",
    "Precio por Vara $": "$280.00",
    "Precio por Vara L.": '"L6,910.40"',
    "Precio por Metro $.": '"$1,494.00"',
    "Precio por Metros L.": '"L8,261.43"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T39",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    EnlaceFazWaz: "",
    EnlaceWhatsApp: "https://wa.me/p/5543019672464371/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/CrWC4xtOoIK/?img_index=1",
    WebAloha: "Terreno en Lomas del Mayab T39 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T41",
    Nombre: "Terreno de 6000 v en el hatillo",
    Documento: "T41.pdf",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: '"$301,458.67"',
    PrecioLempiras: '"L7,440,000.00"',
    UbicacionGoogle: "El Hatillo - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.27635049",
    Longitud: "-87.04843311",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "1240",
    Metros2: "1037.46",
    "Precio por Vara $": "$243.11",
    "Precio por Vara L.": '"L6,000.00"',
    "Precio por Metro $.": '"$1,240.00"',
    "Precio por Metros L.": '"L7,171.36"',
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T41",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    EnlaceFazWaz: "",
    EnlaceWhatsApp: "https://wa.me/p/6410315768983293/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/Cky3y64OZrL/?img_index=1",
    WebAloha: "Terreno en el Hatillo T41 – Real Estate (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T42",
    Nombre: "Terreno en Mateo",
    Documento: "T42.pdf",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: '"$269,448.95"',
    PrecioLempiras: '"L6,650,000.00"',
    UbicacionGoogle: "Mateo Tapias - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.09477796",
    Longitud: "-87.169511",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "10222",
    Metros2: "8541.76",
    "Precio por Vara $": "$26.36",
    "Precio por Vara L.": "L650.56",
    "Precio por Metro $.": '"$10,222.00"',
    "Precio por Metros L.": "L778.53",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T42",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    EnlaceFazWaz: "",
    EnlaceWhatsApp: "https://wa.me/p/5897106160325948/50494109350",
    EnlaceInstagram: "https://www.instagram.com/p/Cj6JNwpuPhb/?img_index=2",
    WebAloha: "Terreno en Mateo T42 – Real Estate (alohasaas.online)",
    EnlaceTikTok:
      '"(99+)Terreno en Mateo A La Venta 🌲 10,222 varas cuadradas 6,650,000 lmps E... | TikTok"',
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C42",
    Nombre: "Casa de dos pisos Estilo Minimalista",
    Documento: "C42.pdf",
    UbicacionEscrita: "San Pedro Sula",
    PrecioDolares: '"$187,800.00"',
    PrecioLempiras: '"L4,634,904.00"',
    UbicacionGoogle: "https://maps.app.goo.gl/LoBZX8erhBasEnHB7",
    Ciudad: "San Pedro Sula",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.52671127",
    Longitud: "-87.96489009",
    DirectaOCompartida: "",
    NCompartidos: "",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "308",
    Metros2: "125",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "3",
    NBanios: "2",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C42",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24":
      "Casa de dos pisos Estilo Minimalista | 3 Recamaras por 4634904.00 en San Pedro Sula (encuentra24.com)",
    EnlaceFazWaz:
      '"Casa de 3 Habitación en Venta en San Pedro Sula, Cortes for L4,634,904 | U1744412 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/8164975193531201/50494109350",
    EnlaceInstagram: "Pendiente",
    WebAloha:
      "Se vende Casa de dos pisos Estilo Minimalista en Colonia Sitratelh San Pedro Sula – Bienes Raíces (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/1253245458708316/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C44",
    Nombre: "Casa en Residencial Genova C44",
    Documento: "C44.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$300,000.00"',
    PrecioLempiras: '"L7,404,000.00"',
    UbicacionGoogle: "Residencial Genova - Google Maps",
    Ciudad: "La Ceiba",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.77561854",
    Longitud: "-86.76963861",
    DirectaOCompartida: "Directa",
    NCompartidos: "-",
    ContactoPropietario: "Nahum Irias",
    TelefonoPropietario: "3379-1330",
    Varas2: "401.59",
    Metros2: "280",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "3",
    NBanios: "3",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C44",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24":
      "Se vende casa en Residencial Genova La Ceiba Atlántida | 3 Recamaras por 7404000.00 en La Ceiba (encuentra24.com)",
    EnlaceFazWaz:
      '"Casa de 3 Habitación en Venta en La Ceiba, Atlantida for L7,404,000 | U1757614 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/25376681651978480/50494109350",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha:
      "Se vende casa en Residencial Genova La Ceiba Atlántida – Bienes Raíces (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/719683630281466/",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "C45",
    Nombre: "Casa con Terreno en Valle de Angeles",
    Documento: "C45.pdf",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: '"$81,037.28"',
    PrecioLempiras: '"L2,000,000.00"',
    UbicacionGoogle: "Valle de angeles - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.07876532",
    Longitud: "-87.163809",
    DirectaOCompartida: "Compartida",
    NCompartidos: "2",
    ContactoPropietario: "Bienes y Raices Grupo Hogar/ Margarita",
    TelefonoPropietario: "8815-1606",
    Varas2: "4400",
    Metros2: "3680.04",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "2",
    NBanios: "1",
    Estacionamiento: "SI",
    Amueblado: "SI",
    Fotos: "C45",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24":
      "Lotes y Terrenos Valle de Ángeles | venta | Se vende Casa con terreno en Valle de Angeles C45 : HNL 2000000.00 (encuentra24.com)",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en Valle De Angeles, Francisco Morazan for L2,000,000 | U1758086 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/25391751610423435/50494109350",
    EnlaceInstagram: "",
    WebAloha:
      "Se vende terreno con casa en venta en Valle de Ángeles – Bienes Raíces (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T53",
    Nombre: "40 Manzanas en laguna del cacao",
    Documento: "T53.pdf",
    UbicacionEscrita: "Jutiapa",
    PrecioDolares: '"$648,298.22"',
    PrecioLempiras: '"L16,000,000.00"',
    UbicacionGoogle: "https://maps.app.goo.gl/T29kGvRY3hnJ36d56",
    Ciudad: "Atlantida",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.80181825",
    Longitud: "-86.54165629",
    DirectaOCompartida: "Directa",
    NCompartidos: "-",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "400000",
    Metros2: "334360",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T53",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24":
      "Lotes y Terrenos Jutiapa | venta | Se venden 40 manzanas en Laguna del Cacao : HNL 9872000.00 (encuentra24.com)",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en Jutiapa, Atlantida for L16,000,000 | U1746682 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "https://wa.me/p/6871954369577315/50494109350",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha:
      "Se venden 40 manzanas en laguna del cacao – Real Estate (alohasaas.online)",
    EnlaceTikTok:
      "https://www.tiktok.com/@alohahome.hn/video/7346014183781059883?is_from_webapp=1&sender_device=pc&web_id=7309328079892530694",
    EnlaceFacebook:
      "https://www.facebook.com/marketplace/item/6850164458421037",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T54",
    Nombre: "13 Manzanas en Valle de Angeles",
    Documento: "T54 (1).pdf",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: '"$62,668.11"',
    PrecioLempiras: '"L1,546,649.00"',
    UbicacionGoogle: "Valle de angeles - Google Maps",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "14.07883818",
    Longitud: "-87.16396991",
    DirectaOCompartida: "-",
    NCompartidos: "*",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "62720",
    Metros2: "52435",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T54",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24":
      "Lotes y Terrenos Valle de Ángeles | venta | (T54) Venta de 13 manzanas en Valle de Ángeles. : HNL 1546649.00 (encuentra24.com)",
    EnlaceFazWaz:
      '"Terreno (Parcela) de en Venta en Valle De Angeles, Francisco Morazan for L1,546,649 | U1759040 (fazwaz.com.hn)"',
    EnlaceWhatsApp: "",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha:
      "13 manzanas en Valle de Ángeles – Bienes Raíces (alohasaas.online)",
    EnlaceTikTok:
      "https://www.tiktok.com/@alohahome.hn/video/7346012237921946926?is_from_webapp=1&sender_device=pc&web_id=7309328079892530694",
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T55",
    Nombre: "Terreno Olanchito Yoro",
    Documento: "T55.pdf",
    UbicacionEscrita: "Yoro",
    PrecioDolares: '"$153,970.83"',
    PrecioLempiras: '"L3,800,000.00"',
    UbicacionGoogle: "https://maps.app.goo.gl/k85cNVEdRF4zijtp9?g_st=iw",
    Ciudad: "Yoro",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.50768376",
    Longitud: "-86.57250842",
    DirectaOCompartida: "-",
    NCompartidos: "-",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "525.64",
    Metros2: "366.49",
    "Precio por Vara $": "",
    "Precio por Vara L.": "",
    "Precio por Metro $.": "",
    "Precio por Metros L.": "",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T55",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    EnlaceFazWaz: "",
    EnlaceWhatsApp: "",
    EnlaceInstagram: "Aloha (@alohahome.hn) • Fotos y videos de Instagram",
    WebAloha:
      '"Terreno con obra de construcción en Olanchito, Yoro – Bienes Raíces (alohasaas.online)"',
    EnlaceTikTok: "(99+)AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
  {
    Codigo: "T52",
    Nombre: '"7 manzanas en Granadita, La Ceiba"',
    Documento: "T52.pdf",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: '"$769,854.13"',
    PrecioLempiras: '"L19,000,000.00"',
    UbicacionGoogle: '"15°47\'07.1""N 86°36\'36.3""W - Google Maps"',
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    Oferta: "Venta",
    Latitud: "15.78860113",
    Longitud: "-86.61059945",
    DirectaOCompartida: "Directa",
    NCompartidos: "-",
    ContactoPropietario: "Luis Castillo",
    TelefonoPropietario: "9995-1556",
    Varas2: "83748.64",
    Metros2: "70000",
    "Precio por Vara $": "$9.19",
    "Precio por Vara L.": "L226.87",
    "Precio por Metro $.": '"$83,748.64"',
    "Precio por Metros L.": "L271.43",
    NHabitaciones: "",
    NBanios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "T52",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    EnlaceFazWaz: "",
    EnlaceWhatsApp: "https://wa.me/p/7203694959708315/50494109350",
    EnlaceInstagram: "pendiente",
    WebAloha:
      "Terreno de 7 manzanas en Aldea la Granadita – Bienes Raíces (alohasaas.online)",
    EnlaceTikTok: "AlohaHome.hn (@alohahome.hn) | TikTok",
    EnlaceFacebook: "",
    EnlaceYoutube: "",
    EnlaceLinkedln: "",
    Adicional: "",
  },
];

interface PropiedadBase {
  codigo: string;
  nombre: string;
  tipoDePropiedad: "Terreno" | "Casa" | "Edificio" | "Apartamento";
  compartidaODirecta: "Compartida" | "Directa" | "";
  ubicacionGoogleMaps: string;
  direccion: string;
  ciudad: string;
  precioDolares: number;
  precioLempiras: number;
  oferta: "Venta" | "Alquiler";
  observaciones: string;
  imagenes: string[];
}

interface Casa extends PropiedadBase {
  nPlantas: number;
  nHabitaciones: number;
  nBanios: number;
  nEstacionamientos: number;
  tienePatio: boolean;
  estaAmueblada: boolean;
}

interface Terreno extends PropiedadBase {
  varas2: number;
  metros2: number;
}

const casas: Casa[] = propiedades
  .filter((p) =>
    ["CASA", "EDIFICIO", "APARTAMENTO"].includes(
      p.TipoPropiedad?.toUpperCase()?.trim()
    )
  )
  .map((p) => {
    const {
      Codigo: codigo,
      Nombre: nombre,
      Ciudad: ciudad,
      PrecioDolares: precioDolares,
      PrecioLempiras: precioLempiras,
      UbicacionGoogle: ubicacionGoogleMaps,
      Amueblado: estaAmueblada,
      NBanios: nBanios,
      Estacionamiento: nEstacionamientos,
      Oferta: oferta,
      NHabitaciones: nHabitaciones,
      Adicional: observaciones,
      DirectaOCompartida: directaOCompartida,
    } = p;

    const ofertaSanitizada =
      oferta?.toUpperCase()?.trim() === "VENTA" ? "Venta" : "Alquiler";

    const numeroDeBanios = parseInt(nBanios.replace(/[^0-9]/g, ""));

    const tieneEstacionamiento =
      nEstacionamientos.toUpperCase().trim() === "SI";

    const numeroDeEstacionamientos = parseInt(
      nEstacionamientos.replace(/[^0-9]/g, "") || tieneEstacionamiento
        ? "1"
        : "0"
    );
    const estaAmuebladaSanitizada = estaAmueblada.toUpperCase().trim() === "SI";
    const numeroDeHabitaciones = parseInt(nHabitaciones.replace(/[^0-9]/g, ""));

    let newDirectaOCompartida = directaOCompartida.toUpperCase().trim();
    newDirectaOCompartida = newDirectaOCompartida.replace("DIRECTO", "DIRECTA");
    newDirectaOCompartida = newDirectaOCompartida.replace(
      "COMPARTIDO",
      "COMPARTIDA"
    );

    newDirectaOCompartida = (
      newDirectaOCompartida === "DIRECTA"
        ? "Directa"
        : newDirectaOCompartida === "COMPARTIDA"
        ? "Compartida"
        : ""
    ) as "Compartida" | "Directa" | "";

    return {
      codigo,
      nombre,
      tipoDePropiedad: "Casa",
      ubicacionGoogleMaps,
      direccion: p.UbicacionEscrita,
      ciudad,
      compartidaODirecta: newDirectaOCompartida as
        | "Compartida"
        | "Directa"
        | "",
      precioDolares: parseFloat(precioDolares.replace(/[^0-9.]/g, "")),
      precioLempiras: parseFloat(precioLempiras.replace(/[^0-9.]/g, "")),
      oferta: ofertaSanitizada,
      observaciones,
      imagenes: [],
      nPlantas: 1,
      nHabitaciones: numeroDeHabitaciones,
      nBanios: numeroDeBanios,
      nEstacionamientos: numeroDeEstacionamientos,
      tienePatio: false,
      estaAmueblada: estaAmuebladaSanitizada,
    };
  });

const terrenos: Terreno[] = propiedades
  .filter((p) => p.TipoPropiedad?.toUpperCase()?.trim() === "TERRENO")
  .map((p) => {
    const {
      Codigo: codigo,
      Nombre: nombre,
      Ciudad: ciudad,
      PrecioDolares: precioDolares,
      PrecioLempiras: precioLempiras,
      UbicacionGoogle: ubicacionGoogleMaps,
      Varas2: varas2,
      Metros2: metros2,
      Oferta: oferta,
      Adicional: observaciones,
      DirectaOCompartida: directaOCompartida,
    } = p;

    const ofertaSanitizada =
      oferta?.toUpperCase()?.trim() === "VENTA" ? "Venta" : "Alquiler";

    let newDirectaOCompartida = directaOCompartida.toUpperCase().trim();
    newDirectaOCompartida = newDirectaOCompartida.replace("DIRECTO", "DIRECTA");
    newDirectaOCompartida = newDirectaOCompartida.replace(
      "COMPARTIDO",
      "COMPARTIDA"
    );

    newDirectaOCompartida =
      newDirectaOCompartida === "DIRECTA"
        ? "Directa"
        : newDirectaOCompartida === "COMPARTIDA"
        ? "Compartida"
        : "";

    return {
      codigo,
      nombre,
      tipoDePropiedad: "Terreno",
      ubicacionGoogleMaps,
      direccion: p.UbicacionEscrita,
      compartidaODirecta: newDirectaOCompartida as
        | "Compartida"
        | "Directa"
        | "",
      ciudad,
      precioDolares: parseFloat(precioDolares.replace(/[^0-9.]/g, "")),
      precioLempiras: parseFloat(precioLempiras.replace(/[^0-9.]/g, "")),
      oferta: ofertaSanitizada,
      observaciones,
      imagenes: [],
      varas2: parseFloat(varas2.replace(/[^0-9.]/g, "")),
      metros2: parseFloat(metros2.replace(/[^0-9.]/g, "")),
    };
  });

console.log(casas);
// console.log(casas.map((c) => c.codigo));
// console.log(terrenos);
