const propiedades = [
  {
    Codigo: "LR3",
    Nombre: "Locales en Colonia Lomas Del Guijarro",
    Documento: "",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: "$1,744.00",
    PrecioLempiras: "L43,041.92",
    UbicacionGoogle: "https://maps.app.goo.gl/ioTLatgKHSoUqte26",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Local/Renta",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Alquiler",
    Latitud: "14.09364948",
    Longitud: "-87.18492085",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "",
    Metros2: "98",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "",
    Banios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "LR3",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "pendiente",
    "Enlace encuentra24": "pendiente",
    "Enlace FazWaz": "pendiente",
    "Enlace WhatsApp": "pendiente",
    "Enlace Instagram": "pendiente",
    "Web Aloha": "pendiente",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional:
      '"Hay mas de un local. Renta de Locales Colonia Lomas del Guijarro: disponibilidad Local 57m2 renta  $ 1,014.60  Local 58 m2 renta $ 1032.40 Local 75 m2 renta $ 1335.0 Local 98m2 renta $ 1744.40 Local 135 m2 renta $ 2403.00 $ 13 el metro cuadrado +$ 2.85 gastos comunes, agua y luz por aparte. Hay estacionamiento."',
  },
  {
    Codigo: "T56",
    Nombre: "Terreno en Santa Ana, Fco. Morazan",
    Documento: "",
    UbicacionEscrita: "Santa Ana",
    PrecioDolares: "$161,683.55",
    PrecioLempiras: "L3,990,350.00",
    UbicacionGoogle: "https://maps.app.goo.gl/RNwarnTmr4wgN5zv5",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "13.92928779",
    Longitud: "-87.27123881",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "11401",
    Metros2: "7966",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "",
    Banios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
  {
    Codigo: "LR4",
    Nombre: "Local en renta Boulevard Morazan",
    Documento: "",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: "$793.84",
    PrecioLempiras: "L19,592.00",
    UbicacionGoogle: "https://maps.app.goo.gl/nbtjkPYsW3k9cTQr7",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Local/Renta",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Alquiler",
    Latitud: "14.10049601",
    Longitud: "-87.18240974",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "",
    Metros2: "32",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "",
    Banios: "1",
    Estacionamiento: "1",
    Amueblado: "SI",
    Fotos: "LR4",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
  {
    Codigo: "C46",
    Nombre: "Casa Residencial El Sauce",
    Documento: "",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: "$335,000.00",
    PrecioLempiras: "L8,267,800.00",
    UbicacionGoogle: "https://maps.app.goo.gl/eQauHG2t2KJsE8oV6",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "14.03932632",
    Longitud: "-87.23040122",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "",
    Metros2: "",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "4",
    Banios: "4",
    Estacionamiento: "2",
    Amueblado: "SI",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
  {
    Codigo: "C47",
    Nombre: "2 propiedades en la Colonia Santa Fe",
    Documento: "",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: "$182,333.87",
    PrecioLempiras: "L4,500,000.00",
    UbicacionGoogle: "https://maps.app.goo.gl/9dgbzmEtx5WaDce17",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "14.09830825",
    Longitud: "-87.22607884",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "",
    Metros2: "",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "3",
    Banios: "2",
    Estacionamiento: "1",
    Amueblado: "NO",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional:
      "Primera Propiedad consta de 3 apartamentos: 1)Sala, comedor, cocina con lavatrasto, 2 habitaciones, un ba�o con cer�mica, pila de lavado forrada de cer�mica, bodega, instalaci�n de lavadora, 2 tanques de reserva de agua, patio con cer�mica. 2) Tambi�n otro apartamento de 2 habitaciones sala, comedor, cocina con lavatrastos, 2 habitaciones, un ba�o con cer�mica, instalaci�n de lavadora, tanque de reserva de agua, patio con firme de cer�mica. 3) Y un ultimo apartamento de 2 habitaciones sala, cocineta con lavatrastos, �rea de lavander�a, pila de lavado, un ba�o, tanque de reserva de agua. Segunda propiedad consta: de una casa y un Local. 1) Segunda propiedad consta de una casa con sala, comedor, cocina, 2 habitaciones un ba�o, �rea de lavander�a, pila de lavado, un estacionamiento, terraza, loza en el tercer piso. 2) Y un local comercial en el primer nivel.",
  },
  {
    Codigo: "C48",
    Nombre: "2 casas en Residencial Campo Verde en Amarateca",
    Documento: "",
    UbicacionEscrita: "Amarateca",
    PrecioDolares: "$28,363.05",
    PrecioLempiras: "L700,000.00",
    UbicacionGoogle: "https://maps.app.goo.gl/zMaHiV4F6Q4TXEue7",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "14.23598174",
    Longitud: "-87.39016849",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "250",
    Metros2: "",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "2",
    Banios: "1",
    Estacionamiento: "1",
    Amueblado: "NO",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
  {
    Codigo: "LR5",
    Nombre: "Alquiler Local Edificio Colonia San Carlos",
    Documento: "",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: "$5,200.00",
    PrecioLempiras: "L128,336.00",
    UbicacionGoogle: "https://maps.app.goo.gl/iL8ZjyYTsnmvEerJ6",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Local/Renta",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Alquiler",
    Latitud: "14.10117213",
    Longitud: "-87.18845084",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "",
    Metros2: "",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "",
    Banios: "",
    Estacionamiento: "10",
    Amueblado: "SI",
    Fotos: "LR5",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
  {
    Codigo: "T57",
    Nombre: "Terreno en Colonia El Pedrero Santa Lucia",
    Documento: "",
    UbicacionEscrita: "Santa lucia",
    PrecioDolares: "$48,622.37",
    PrecioLempiras: "L1,200,000.00",
    UbicacionGoogle: "https://maps.app.goo.gl/jndcsJbkvb47aSBU9",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "14.11075727",
    Longitud: "-87.10844666",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "1000",
    Metros2: "697.22",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "",
    Banios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
  {
    Codigo: "ED4",
    Nombre: "Edificio septima avenida de comayaguela",
    Documento: "",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: "$40,518.64",
    PrecioLempiras: "L1,000,000.00",
    UbicacionGoogle: "https://maps.app.goo.gl/pVX6EcVvL2WUL9pw5",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Edificio",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "14.08943899",
    Longitud: "-87.21153499",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "800",
    Metros2: "",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "11",
    Banios: "3",
    Estacionamiento: "-",
    Amueblado: "NO",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional:
      "Consta de 3 niveles: Primer Nivel: Es de uso comercial, topografia plana, cuenta con todos los servicios p�blicos b�sicos, piso de cer�mica y concreto, paredes ladrillo raf�n, repello en losa, tanque de reserva de agua, muebles de cocina de concreto. 2 oficinas, A/C, �rea de recepci�n, sala de ventas, �rea de despacho, 3 sanitarios, 11 habitaciones, cocina con lavatrasto. Segundo nivel: una pila, tanque de reserva de agua, 2 bodegas, 2 minibodegas, �rea grande de bodega, Tercer nivel: 3 bodegas amplias y mas espacios. Area del terreno 800 vrs2 1700 m2 de construcci�n Precio de Venta Lps. 10,000 000 ( 10 millones de lempiras )",
  },
  {
    Codigo: "C49",
    Nombre: "Casa Colonia El Country",
    Documento: "",
    UbicacionEscrita: "Tegucigalpa",
    PrecioDolares: "$101,296.60",
    PrecioLempiras: "L2,500,000.00",
    UbicacionGoogle: "https://maps.app.goo.gl/GG7kWMAbTMo8vnvH6",
    Ciudad: "Francisco Morazan",
    TipoPropiedad: "Casa",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "14.09409388",
    Longitud: "-87.21903162",
    PDirectaOCompartida: "Compartido",
    NoCompartidos: "1",
    ContactoPropietario: "Bienes y raices cenra",
    TelefonoPropietario: "9738-7354",
    Varas2: "195.4",
    Metros2: "",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "4",
    Banios: "2",
    Estacionamiento: "-",
    Amueblado: "SI",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
  {
    Codigo: "T58",
    Nombre: "Terreno en residencial el toronjal",
    Documento: "",
    UbicacionEscrita: "La Ceiba",
    PrecioDolares: "$149,918.96",
    PrecioLempiras: "L3,700,000.00",
    UbicacionGoogle: "https://maps.app.goo.gl/w5P6HFYmmpqptysg7",
    Ciudad: "La Ceiba",
    TipoPropiedad: "Terreno",
    Estatus: "Disponible",
    OfertaInmobiliaria: "Venta",
    Latitud: "15.77649976",
    Longitud: "-86.79371457",
    PDirectaOCompartida: "Directo",
    NoCompartidos: "-",
    ContactoPropietario: "",
    TelefonoPropietario: "",
    Varas2: "1072.44",
    Metros2: "747.73",
    PrecioVaraD: "",
    PrecioVaraL: "",
    PrecioMetroD: "",
    PrecioMetroL: "",
    Habitaciones: "",
    Banios: "",
    Estacionamiento: "",
    Amueblado: "",
    Fotos: "",
    "Enlace Inmobiliaria.com": "",
    Planos: "",
    "Enlace quierocasa.hn": "",
    "Enlace encuentra24": "",
    "Enlace FazWaz": "",
    "Enlace WhatsApp": "",
    "Enlace Instagram": "",
    "Web Aloha": "",
    "Enlace Tik Tok": "",
    "Enlace Facebook": "",
    "Enlace Youtube": "",
    "Enlace Twitter": "",
    "Enlace Linkedln": "",
    Adicional: "",
  },
];

interface PropiedadBase {
  codigo: string;
  nombre: string;
  tipoDePropiedad: "Terreno" | "Casa" | "Edificio" | "Apartamento";
  compartidaODirecta: "Compartida" | "Directa" | "";
  ubicacionGoogleMaps: string;
  direccion: string;
  ciudad: string;
  precioDolares: number;
  precioLempiras: number;
  oferta: "Venta" | "Alquiler";
  observaciones: string;
  imagenes: string[];
}

interface Casa extends PropiedadBase {
  nPlantas: number;
  nHabitaciones: number;
  nBanios: number;
  nEstacionamientos: number;
  tienePatio: boolean;
  estaAmueblada: boolean;
}

interface Terreno extends PropiedadBase {
  varas2: number;
  metros2: number;
}

const casas: Casa[] = propiedades
  .filter((p) =>
    ["CASA", "EDIFICIO", "APARTAMENTO", "LOCAL/RENTA"].includes(
      p.TipoPropiedad?.toUpperCase()?.trim()
    )
  )
  .map((p) => {
    const {
      Codigo: codigo,
      Nombre: nombre,
      Ciudad: ciudad,
      PrecioDolares: precioDolares,
      PrecioLempiras: precioLempiras,
      UbicacionGoogle: ubicacionGoogleMaps,
      Amueblado: estaAmueblada,
      Banios: nBanios,
      Estacionamiento: nEstacionamientos,
      OfertaInmobiliaria: oferta,
      Habitaciones: nHabitaciones,
      Adicional: observaciones,
      PDirectaOCompartida: directaOCompartida,
    } = p;

    const ofertaSanitizada =
      oferta?.toUpperCase()?.trim() === "VENTA" ? "Venta" : "Alquiler";

    const numeroDeBanios = parseInt(nBanios.replace(/[^0-9]/g, ""));

    const tieneEstacionamiento =
      nEstacionamientos.toUpperCase().trim() === "SI";

    const numeroDeEstacionamientos = parseInt(
      nEstacionamientos.replace(/[^0-9]/g, "") || tieneEstacionamiento
        ? "1"
        : "0"
    );
    const estaAmuebladaSanitizada = estaAmueblada.toUpperCase().trim() === "SI";
    const numeroDeHabitaciones = parseInt(nHabitaciones.replace(/[^0-9]/g, ""));

    let newDirectaOCompartida = directaOCompartida.toUpperCase().trim();
    newDirectaOCompartida = newDirectaOCompartida.replace("DIRECTO", "DIRECTA");
    newDirectaOCompartida = newDirectaOCompartida.replace(
      "COMPARTIDO",
      "COMPARTIDA"
    );

    newDirectaOCompartida = (
      newDirectaOCompartida === "DIRECTA"
        ? "Directa"
        : newDirectaOCompartida === "COMPARTIDA"
        ? "Compartida"
        : ""
    ) as "Compartida" | "Directa" | "";

    return {
      codigo,
      nombre,
      tipoDePropiedad: "Casa",
      ubicacionGoogleMaps,
      direccion: p.UbicacionEscrita,
      ciudad,
      compartidaODirecta: newDirectaOCompartida as
        | "Compartida"
        | "Directa"
        | "",
      precioDolares: parseFloat(precioDolares.replace(/[^0-9.]/g, "")),
      precioLempiras: parseFloat(precioLempiras.replace(/[^0-9.]/g, "")),
      oferta: ofertaSanitizada,
      observaciones,
      imagenes: [],
      nPlantas: 1,
      nHabitaciones: numeroDeHabitaciones,
      nBanios: numeroDeBanios,
      nEstacionamientos: numeroDeEstacionamientos,
      tienePatio: false,
      estaAmueblada: estaAmuebladaSanitizada,
    };
  });

const terrenos: Terreno[] = propiedades
  .filter((p) => p.TipoPropiedad?.toUpperCase()?.trim() === "TERRENO")
  .map((p) => {
    const {
      Codigo: codigo,
      Nombre: nombre,
      Ciudad: ciudad,
      PrecioDolares: precioDolares,
      PrecioLempiras: precioLempiras,
      UbicacionGoogle: ubicacionGoogleMaps,
      Varas2: varas2,
      Metros2: metros2,
      OfertaInmobiliaria: oferta,
      Adicional: observaciones,
      PDirectaOCompartida: directaOCompartida,
    } = p;

    const ofertaSanitizada =
      oferta?.toUpperCase()?.trim() === "VENTA" ? "Venta" : "Alquiler";

    let newDirectaOCompartida = directaOCompartida.toUpperCase().trim();
    newDirectaOCompartida = newDirectaOCompartida.replace("DIRECTO", "DIRECTA");
    newDirectaOCompartida = newDirectaOCompartida.replace(
      "COMPARTIDO",
      "COMPARTIDA"
    );

    newDirectaOCompartida =
      newDirectaOCompartida === "DIRECTA"
        ? "Directa"
        : newDirectaOCompartida === "COMPARTIDA"
        ? "Compartida"
        : "";

    return {
      codigo,
      nombre,
      tipoDePropiedad: "Terreno",
      ubicacionGoogleMaps,
      direccion: p.UbicacionEscrita,
      compartidaODirecta: newDirectaOCompartida as
        | "Compartida"
        | "Directa"
        | "",
      ciudad,
      precioDolares: parseFloat(precioDolares.replace(/[^0-9.]/g, "")),
      precioLempiras: parseFloat(precioLempiras.replace(/[^0-9.]/g, "")),
      oferta: ofertaSanitizada,
      observaciones,
      imagenes: [],
      varas2: parseFloat(varas2.replace(/[^0-9.]/g, "")),
      metros2: parseFloat(metros2.replace(/[^0-9.]/g, "")),
    };
  });

// console.log(casas);
console.log(casas.map((c) => c.codigo));
console.log(terrenos.map((c) => c.codigo));
// console.log(terrenos);
