import type { Casa, Terreno } from "../types/types";

export const casas: Casa[] = [
  {
    codigo: "ED1",
    nombre: '"Edificio, Colonia Pizzati"',
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/q6ZPgsJdPDYCzGeL7",
    direccion: '"Colonia Pizzatti en La Ciudad de la Ceiba, Atlántida."',
    ciudad: "La Ceiba",
    compartidaODirecta: "Compartida",
    precioDolares: 200000,
    precioLempiras: 4800000,
    oferta: "Venta",
    observaciones: "Edificio de dos niveles con 7 apartamentos",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: NaN,
    nBanios: NaN,
    nEstacionamientos: 0,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C6",
    nombre: "Villa en Palma Real L6",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/qLeey7AAD83ws8cP6",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 175000,
    precioLempiras: 4319000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C5",
    nombre: "Villa en Palma Real amueblada L13",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/qLeey7AAD83ws8cP6",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 220268,
    precioLempiras: 5436214.24,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C4",
    nombre: "Casa Residencial El Naranjal",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/poXhnoybk3j7fdRo8",
    direccion: "Residencial El Naranjal",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 365475.57,
    precioLempiras: 9019937,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 4,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C1",
    nombre: "Villa en Palma Real",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/73UzFBk3Q2WyHpoY9",
    direccion: '"Palma Real, La Ceiba Atlantida "',
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 230000,
    precioLempiras: 5676400,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C26",
    nombre: "Casa redisencial Genova",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/SDPzvkz5arJGNLnVA",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 157127.23,
    precioLempiras: 3877900,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "AP21",
    nombre: "Apartamento en renta SPS",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/GLCu2UELbj5NDJMY9",
    direccion: "San Pedro Sula",
    ciudad: "San Pedro Sula",
    compartidaODirecta: "Directa",
    precioDolares: 1350,
    precioLempiras: 33318,
    oferta: "Alquiler",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C43",
    nombre: "Villa en Palma Real",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/6Y5tKZ3hhzE5h7iB8",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 130000,
    precioLempiras: 3208400,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "ED2",
    nombre: '"Edificio, en Barrio Solares Nuevos"',
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/p3DVFPsTRjsbFX9V8",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 283630.47,
    precioLempiras: 7000000,
    oferta: "Alquiler",
    observaciones:
      '"Apartamento 1  de dos habitaciones 10,000  lempiras.    3 apartamentos de 1 habitación 8,000 lempiras cada uno.                                                                                                               Local planta baja 40,000 lempiras negociable      "',
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 5,
    nBanios: 5,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "ED3",
    nombre: "Edificio y casa Barrio Alvarado 20 Avenida 14 de julio",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/P5un9Up4YN3e7gQo9",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 648298.22,
    precioLempiras: 16000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C8",
    nombre: "Casa Miramontes",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/ncDHZVYshCK2UiHW8",
    direccion: "Tegucigalpa",
    ciudad: "Francisco Morazan",
    compartidaODirecta: "",
    precioDolares: 323886,
    precioLempiras: 8000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 1,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: false,
  },
  {
    codigo: "C42",
    nombre: "Casa de dos pisos Estilo Minimalista",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/nczQFNTK4eHxvW768",
    direccion: "San Pedro Sula",
    ciudad: "San Pedro Sula",
    compartidaODirecta: "",
    precioDolares: 187800,
    precioLempiras: 4634904,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C44",
    nombre: "Casa en Residencial Genova C44",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/Ekv7L9TUzeUg3zHNA",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 300000,
    precioLempiras: 7404000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C45",
    nombre: "Casa con Terreno en Valle de Angeles",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/3gUxmJAn1orK1Tf18",
    direccion: "Tegucigalpa",
    ciudad: "Francisco Morazan",
    compartidaODirecta: "Compartida",
    precioDolares: 81037.28,
    precioLempiras: 2000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 1,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
];

export const terrenos: Terreno[] = [
  {
    codigo: "TA1",
    nombre: '"Terreno en alquiler, Talanga "',
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/egYsL85pNuPsdm8m9",
    direccion:
      "Ubicado en la zona comercial donde acaban de terminar de hacer los cuatro carriles en Talanga .",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 607.78,
    precioLempiras: 15000,
    oferta: "Alquiler",
    observaciones: "",
    imagenes: [],
    varas2: 354.47,
    metros2: 246.15,
  },
  {
    codigo: "T9",
    nombre: "Terreno frente a playa Puerto Cortes",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/GSfV1ZLkTqdcxFSE9",
    direccion: "Puerto Cortes",
    compartidaODirecta: "",
    ciudad: "Puerto Cortes",
    precioDolares: 393030.79,
    precioLempiras: 9700000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 3236,
    metros2: 2705,
  },
  {
    codigo: "T8",
    nombre: "Terreno barrio independencia",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/GN6DmacntZ4NkjUS6",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 149918.96,
    precioLempiras: 3700000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 425,
    metros2: 297.1,
  },
  {
    codigo: "T7",
    nombre: "10 Manzanas a 695 la vara en la Ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/CibU2suuyWR4FBxb6",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 2816045.38,
    precioLempiras: 69500000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: NaN,
    metros2: NaN,
  },
  {
    codigo: "T6",
    nombre: "Terreno en valle de angeles",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/oKsBWjFFYNgfLrhS9",
    direccion: "Valle de angeles",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 151944.89,
    precioLempiras: 3750000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 3000,
    metros2: 2743.2,
  },
  {
    codigo: "T3",
    nombre: "Terreno con casa con acceso a playa",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/gKKEMFxQoto3vmZb7",
    direccion: "Puerto Cortes",
    compartidaODirecta: "",
    ciudad: "Puerto Cortes",
    precioDolares: 1215559.16,
    precioLempiras: 30000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 9267.84,
    metros2: 7746,
  },
  {
    codigo: "T25",
    nombre: "Terreno Aldea de el Ovejo",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/DCyzm7xZGkfRPYb88",
    direccion:
      '"Aldea de El Ovejo, municipio de Lepaterique, Francisco Morazán, Honduras, C.A"',
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 182333.87,
    precioLempiras: 4500000,
    oferta: "Venta",
    observaciones: '"Cuenta con café variedad Lempira en producción 16 palos',
    imagenes: [],
    varas2: NaN,
    metros2: NaN,
  },
  {
    codigo: "T20",
    nombre: "Terreno para bodega",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/fGvRg5x3V1Mrh92XA",
    direccion: '"Al lado de la escuela internacional , Tegucigalpa "',
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 1050000,
    precioLempiras: 25914000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 3000,
    metros2: 2507.715,
  },
  {
    codigo: "T18",
    nombre: "Terreno cercano a cascadas mall",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/zg3Ww2bpb9SDVmjAA",
    direccion: "Cercano a cascadas mall",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 9300000,
    precioLempiras: 229524000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 15500,
    metros2: 12956.53,
  },
  {
    codigo: "T13",
    nombre: "6 manzanas en Tamara",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/PJnamUB7GBQQqUVp6",
    direccion: "Tamara",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 729335.49,
    precioLempiras: 18000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 60000,
    metros2: 50154.3,
  },
  {
    codigo: "T28",
    nombre: "Terreno en Venta Lomas del Mayab",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/DezApyngiXsHsP3YA",
    direccion: "Lomas del Mayab",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 418320,
    precioLempiras: 10332504,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 1494,
    metros2: 1249.88,
  },
  {
    codigo: "T21",
    nombre: "Terreno frente Aeropuerto",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/KkrDFnDvqWiibQ7V8",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 530794.17,
    precioLempiras: 13100000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 1392,
    metros2: 1163.58,
  },
  {
    codigo: "T45",
    nombre: "Terreno en San Jose de Soroguara",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/sGf8uqY9k9ZGNRmk6",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 202593.19,
    precioLempiras: 5000000,
    oferta: "Alquiler",
    observaciones: "",
    imagenes: [],
    varas2: 1148.85,
    metros2: 958.94,
  },
  {
    codigo: "T2",
    nombre: "10 Manzanas frente al mar en la ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/oAgPpYnjXBLkPex38",
    direccion: '"Sector de Coco Pando, con acceso a la calle 8. "',
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 193800,
    precioLempiras: 4782984,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 193.8,
    metros2: 162,
  },
  {
    codigo: "T46",
    nombre: "Terreno en valle de angeles",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/TNPdS8HWXxsxbFx68",
    direccion: '"Valle de Angeles Aldea las Cabañas, el mirador"',
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 166733.75,
    precioLempiras: 4114989,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 3048.14,
    metros2: 2125.24,
  },
  {
    codigo: "T17",
    nombre: "Terreno Ceiba HN",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/cKkQTk6RLbLtnXEs5",
    direccion: '"La Ceiba, en el Naranjal"',
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 215194.49,
    precioLempiras: 5311000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 1305,
    metros2: 1090.86,
  },
  {
    codigo: "T14",
    nombre: "Terreno en venta la ceiba hn",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/aMDZd1E1gBhZMpDu7",
    direccion: "Colonia D Antoni",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 14586.71,
    precioLempiras: 360000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 218.72,
    metros2: 200,
  },
  {
    codigo: "T12",
    nombre: "Terreno de 2 Manzanas en Ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/QiMfiX1ViT3BZsnt5",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 344408.43,
    precioLempiras: 8500000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: NaN,
    metros2: NaN,
  },
  {
    codigo: "T47",
    nombre: "Terreno en barrio el centro",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/E34hnTJ4V15gX25N7",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 38492.71,
    precioLempiras: 950000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 228.35,
    metros2: 209.02,
  },
  {
    codigo: "T48",
    nombre: '"Terreno a orilla de playa, se ve enfrente cayos cochinos"',
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/qcgrGWMASuYY8qeB9",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 300000,
    precioLempiras: 7404000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 10343.78,
    metros2: 8656.92,
  },
  {
    codigo: "T49",
    nombre: "Terreno 9.55 manzanas Roma La Ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/amfRDU9MFpGWYdEZ9",
    direccion: "La Ceiba",
    compartidaODirecta: "Compartida",
    ciudad: "La Ceiba",
    precioDolares: 1094003.24,
    precioLempiras: 27000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: NaN,
    metros2: NaN,
  },
  {
    codigo: "T50",
    nombre: "Terreno en residencial monte real del bosque",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/amfRDU9MFpGWYdEZ9",
    direccion: "La Ceiba",
    compartidaODirecta: "Compartida",
    ciudad: "La Ceiba",
    precioDolares: 28363.05,
    precioLempiras: 700000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 428.6,
    metros2: 298.82,
  },
  {
    codigo: "T51",
    nombre: "Terrenos cerca del mar en la ensenada",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/EcLfRx5Qovfgkg6f7",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 44570.5,
    precioLempiras: 1100000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 393.42,
    metros2: 275,
  },
  {
    codigo: "T39",
    nombre: "Terreno lomas del Mayab",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/DezApyngiXsHsP3YA",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 418320,
    precioLempiras: 10324137.6,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 1494,
    metros2: 1249.68,
  },
  {
    codigo: "T41",
    nombre: "Terreno de 6000 v en el hatillo",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/7zxstj2xoxtjnzzC6",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 301458.67,
    precioLempiras: 7440000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 1240,
    metros2: 1037.46,
  },
  {
    codigo: "T42",
    nombre: "Terreno en Mateo",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/Si3AhY3nkTxjkRZWA",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 269448.95,
    precioLempiras: 6650000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 10222,
    metros2: 8541.76,
  },
  {
    codigo: "T53",
    nombre: "40 Manzanas en laguna del cacao",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/odB1ECSmWanVw97GA",
    direccion: "Jutiapa",
    compartidaODirecta: "Directa",
    ciudad: "Atlantida",
    precioDolares: 648298.22,
    precioLempiras: 16000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 400000,
    metros2: 334360,
  },
  {
    codigo: "T54",
    nombre: "13 Manzanas en Valle de Angeles",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/3gUxmJAn1orK1Tf18",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 62668.11,
    precioLempiras: 1546649,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 62720,
    metros2: 52435,
  },
  {
    codigo: "T55",
    nombre: "Terreno Olanchito Yoro",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/35kLkmBmZQKXk9ko7",
    direccion: "Yoro",
    compartidaODirecta: "",
    ciudad: "Yoro",
    precioDolares: 153970.83,
    precioLempiras: 3800000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 525.64,
    metros2: 366.49,
  },
  {
    codigo: "T52",
    nombre: '"7 manzanas en Granadita, La Ceiba"',
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/EVVmA4BtDFTD9ZhE6",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 769854.13,
    precioLempiras: 19000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [],
    varas2: 83748.64,
    metros2: 70000,
  },
];
