import type { Casa, Terreno } from "../types/types";

export const casas: Casa[] = [
  {
    codigo: "ED1",
    nombre: "Edificio, Colonia Pizzati",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/q6ZPgsJdPDYCzGeL7",
    direccion: "Colonia Pizzatti en La Ciudad de la Ceiba, Atlántida.",
    ciudad: "La Ceiba",
    compartidaODirecta: "Compartida",
    precioDolares: 200000,
    precioLempiras: 4800000,
    oferta: "Venta",
    observaciones: "Edificio de dos niveles con 7 apartamentos",
    imagenes: ["/ED1/1.jpeg", "/ED1/2.jpeg"],
    nPlantas: 1,
    nHabitaciones: NaN,
    nBanios: NaN,
    nEstacionamientos: 0,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C6",
    nombre: "Villa en Palma Real L6",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/qLeey7AAD83ws8cP6",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 175000,
    precioLempiras: 4319000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C6/1.jpeg",
      "/C6/2.jpeg",
      "/C6/3.jpeg",
      "/C6/4.jpeg",
      "/C6/5.jpeg",
      "/C6/6.jpeg",
      "/C6/7.jpeg",
      "/C6/8.jpeg",
      "/C6/9.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C5",
    nombre: "Villa en Palma Real amueblada L13",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/qLeey7AAD83ws8cP6",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 220268,
    precioLempiras: 5436214.24,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C5/1.jpeg",
      "/C5/2.jpeg",
      "/C5/3.jpeg",
      "/C5/4.jpeg",
      "/C5/5.jpeg",
      "/C5/6.jpeg",
      "/C5/7.jpeg",
      "/C5/8.jpeg",
      "/C5/9.jpeg",
      "/C5/10.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C4",
    nombre: "Casa Residencial El Naranjal",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/poXhnoybk3j7fdRo8",
    direccion: "Residencial El Naranjal",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 365475.57,
    precioLempiras: 9019937,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/C4/1.jpeg", "/C4/2.jpeg", "/C4/3.jpeg"],
    nPlantas: 1,
    nHabitaciones: 4,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C1",
    nombre: "Villa en Palma Real",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/73UzFBk3Q2WyHpoY9",
    direccion: "Palma Real, La Ceiba Atlantida ",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 230000,
    precioLempiras: 5676400,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C1/1.jpeg",
      "/C1/2.jpeg",
      "/C1/3.jpeg",
      "/C1/4.jpeg",
      "/C1/5.jpeg",
      "/C1/6.jpeg",
      "/C1/7.jpeg",
      "/C1/8.jpeg",
      "/C1/9.jpeg",
      "/C1/10.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C26",
    nombre: "Casa redisencial Genova",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/SDPzvkz5arJGNLnVA",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 157127.23,
    precioLempiras: 3877900,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/C26/1.jpeg", "/C26/2.jpeg", "/C26/3.jpeg", "/C26/4.jpeg"],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "AP21",
    nombre: "Apartamento en renta SPS",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/GLCu2UELbj5NDJMY9",
    direccion: "San Pedro Sula",
    ciudad: "San Pedro Sula",
    compartidaODirecta: "Directa",
    precioDolares: 1350,
    precioLempiras: 33318,
    oferta: "Alquiler",
    observaciones: "",
    imagenes: [
      "/AP21/1.jpeg",
      "/AP21/2.jpeg",
      "/AP21/3.jpeg",
      "/AP21/4.jpeg",
      "/AP21/5.jpeg",
      "/AP21/6.jpeg",
      "/AP21/7.jpeg",
      "/AP21/8.jpeg",
      "/AP21/9.jpeg",
      "/AP21/10.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C43",
    nombre: "Villa en Palma Real",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/6Y5tKZ3hhzE5h7iB8",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 130000,
    precioLempiras: 3208400,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C43/1.jpeg",
      "/C43/2.jpeg",
      "/C43/3.jpeg",
      "/C43/4.jpeg",
      "/C43/5.jpeg",
      "/C43/6.jpeg",
      "/C43/7.jpeg",
      "/C43/8.jpeg",
      "/C43/9.jpeg",
      "/C43/10.jpeg",
      "/C43/11.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "ED2",
    nombre: "Edificio, en Barrio Solares Nuevos",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/p3DVFPsTRjsbFX9V8",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 283630.47,
    precioLempiras: 7000000,
    oferta: "Alquiler",
    observaciones:
      "Apartamento 1  de dos habitaciones 10,000  lempiras.    3 apartamentos de 1 habitación 8,000 lempiras cada uno.                                                                                                               Local planta baja 40,000 lempiras negociable      ",
    imagenes: [
      "/ED2/1.jpeg",
      "/ED2/2.jpeg",
      "/ED2/3.jpeg",
      "/ED2/4.jpeg",
      "/ED2/5.jpeg",
      "/ED2/6.jpeg",
      "/ED2/7.jpeg",
      "/ED2/8.jpeg",
      "/ED2/9.jpeg",
      "/ED2/10.jpeg",
      "/ED2/11.jpeg",
      "/ED2/12.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 5,
    nBanios: 5,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "ED3",
    nombre: "Edificio y casa Barrio Alvarado 20 Avenida 14 de julio",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/P5un9Up4YN3e7gQo9",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 648298.22,
    precioLempiras: 16000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/ED3/1.jpeg", "/ED3/2.jpeg", "/ED3/3.jpeg"],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C8",
    nombre: "Casa Miramontes",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/ncDHZVYshCK2UiHW8",
    direccion: "Tegucigalpa",
    ciudad: "Francisco Morazan",
    compartidaODirecta: "",
    precioDolares: 323886,
    precioLempiras: 8000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C8/1.jpeg",
      "/C8/2.jpeg",
      "/C8/3.jpeg",
      "/C8/4.jpeg",
      "/C8/5.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 1,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: false,
  },
  {
    codigo: "C42",
    nombre: "Casa de dos pisos Estilo Minimalista",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/nczQFNTK4eHxvW768",
    direccion: "San Pedro Sula",
    ciudad: "San Pedro Sula",
    compartidaODirecta: "",
    precioDolares: 187800,
    precioLempiras: 4634904,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C42/1.jpeg",
      "/C42/2.jpeg",
      "/C42/3.jpeg",
      "/C42/4.jpeg",
      "/C42/5.jpeg",
      "/C42/6.jpeg",
      "/C42/7.jpeg",
      "/C42/8.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 2,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C44",
    nombre: "Casa en Residencial Genova C44",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/Ekv7L9TUzeUg3zHNA",
    direccion: "La Ceiba",
    ciudad: "La Ceiba",
    compartidaODirecta: "Directa",
    precioDolares: 300000,
    precioLempiras: 7404000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C44/1.jpeg",
      "/C44/2.jpeg",
      "/C44/3.jpeg",
      "/C44/4.jpeg",
      "/C44/5.jpeg",
      "/C44/6.jpeg",
      "/C44/7.jpeg",
      "/C44/8.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 3,
    nBanios: 3,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
  {
    codigo: "C45",
    nombre: "Casa con Terreno en Valle de Angeles",
    tipoDePropiedad: "Casa",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/3gUxmJAn1orK1Tf18",
    direccion: "Tegucigalpa",
    ciudad: "Francisco Morazan",
    compartidaODirecta: "Compartida",
    precioDolares: 81037.28,
    precioLempiras: 2000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/C45/1.jpeg",
      "/C45/2.jpeg",
      "/C45/3.jpeg",
      "/C45/4.jpeg",
      "/C45/5.jpeg",
      "/C45/6.jpeg",
      "/C45/7.jpeg",
      "/C45/8.jpeg",
      "/C45/9.jpeg",
      "/C45/10.jpeg",
    ],
    nPlantas: 1,
    nHabitaciones: 2,
    nBanios: 1,
    nEstacionamientos: 1,
    tienePatio: false,
    estaAmueblada: true,
  },
];

export const terrenos: Terreno[] = [
  {
    codigo: "TA1",
    nombre: "Terreno en alquiler, Talanga ",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/egYsL85pNuPsdm8m9",
    direccion:
      "Ubicado en la zona comercial donde acaban de terminar de hacer los cuatro carriles en Talanga .",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 607.78,
    precioLempiras: 15000,
    oferta: "Alquiler",
    observaciones: "",
    imagenes: [
      "/TA1/1.jpeg",
      "/TA1/2.jpeg",
      "/TA1/3.jpeg",
      "/TA1/4.jpeg",
      "/TA1/5.jpeg",
    ],
    varas2: 354.47,
    metros2: 246.15,
  },
  {
    codigo: "T9",
    nombre: "Terreno frente a playa Puerto Cortes",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/GSfV1ZLkTqdcxFSE9",
    direccion: "Puerto Cortes",
    compartidaODirecta: "",
    ciudad: "Puerto Cortes",
    precioDolares: 393030.79,
    precioLempiras: 9700000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T9/1.jpeg", "/T9/2.jpeg", "/T9/3.jpeg", "/T9/4.jpeg"],
    varas2: 3236,
    metros2: 2261,
  },
  {
    codigo: "T8",
    nombre: "Terreno barrio independencia",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/GN6DmacntZ4NkjUS6",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 149918.96,
    precioLempiras: 3700000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T8/1.jpeg", "/T8/2.jpeg"],
    varas2: 425,
    metros2: 297.1,
  },
  {
    codigo: "T7",
    nombre: "10 Manzanas a 695 la vara en la Ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/CibU2suuyWR4FBxb6",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 2816045.38,
    precioLempiras: 69500000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T7/1.jpeg"],
    varas2: 119600,
    metros2: 83569,
  },
  {
    codigo: "T6",
    nombre: "Terreno en valle de angeles",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/oKsBWjFFYNgfLrhS9",
    direccion: "Valle de angeles",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 151944.89,
    precioLempiras: 3750000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T6/1.jpeg", "/T6/2.jpeg", "/T6/3.jpeg"],
    varas2: 3000,
    metros2: 2096,
  },
  {
    codigo: "T3",
    nombre: "Terreno con casa con acceso a playa",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/gKKEMFxQoto3vmZb7",
    direccion: "Puerto Cortes",
    compartidaODirecta: "",
    ciudad: "Puerto Cortes",
    precioDolares: 1215559.16,
    precioLempiras: 30000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T3/1.jpeg", "/T3/2.jpeg", "/T3/3.jpeg"],
    varas2: 9267.84,
    metros2: 6475,
  },
  {
    codigo: "T25",
    nombre: "Terreno Aldea de el Ovejo",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/DCyzm7xZGkfRPYb88",
    direccion:
      "Aldea de El Ovejo, municipio de Lepaterique, Francisco Morazán, Honduras, C.A",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 182333.87,
    precioLempiras: 4500000,
    oferta: "Venta",
    observaciones: "Cuenta con café variedad Lempira en producción 16 palos",
    imagenes: ["/T25/1.jpeg", "/T25/2.jpeg", "/T25/3.jpeg", "/T25/4.jpeg"],
    varas2: NaN,
    metros2: NaN,
  },
  {
    codigo: "T20",
    nombre: "Terreno para bodega",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/fGvRg5x3V1Mrh92XA",
    direccion: "Al lado de la escuela internacional , Tegucigalpa ",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 1050000,
    precioLempiras: 25914000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T20/1.jpeg", "/T20/2.jpeg", "/T20/3.jpeg"],
    varas2: 3000,
    metros2: 2096,
  },
  {
    codigo: "T18",
    nombre: "Terreno cercano a cascadas mall",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/zg3Ww2bpb9SDVmjAA",
    direccion: "Cercano a cascadas mall",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 9300000,
    precioLempiras: 229524000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T18/1.jpeg", "/T18/2.jpeg"],
    varas2: 15500,
    metros2: 10830,
  },
  {
    codigo: "T13",
    nombre: "6 manzanas en Tamara",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/PJnamUB7GBQQqUVp6",
    direccion: "Tamara",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 729335.49,
    precioLempiras: 18000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T13/1.jpeg", "/T13/2.jpeg", "/T13/3.jpeg"],
    varas2: 60000,
    metros2: 41928,
  },
  {
    codigo: "T28",
    nombre: "Terreno en Venta Lomas del Mayab",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/DezApyngiXsHsP3YA",
    direccion: "Lomas del Mayab",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 418320,
    precioLempiras: 10332504,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T28/1.jpeg", "/T28/2.jpeg"],
    varas2: 1494,
    metros2: 1044,
  },
  {
    codigo: "T21",
    nombre: "Terreno frente Aeropuerto",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/KkrDFnDvqWiibQ7V8",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 530794.17,
    precioLempiras: 13100000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T21/1.jpeg", "/T21/2.jpeg"],
    varas2: 3192,
    metros2: 2230,
  },
  {
    codigo: "T45",
    nombre: "Terreno en San Jose de Soroguara",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/sGf8uqY9k9ZGNRmk6",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 202593.19,
    precioLempiras: 5000000,
    oferta: "Alquiler",
    observaciones: "",
    imagenes: ["/T45/1.jpeg", "/T45/2.jpeg", "/T45/3.jpeg"],
    varas2: 1148.85,
    metros2: 802,
  },
  {
    codigo: "T2",
    nombre: "10 Manzanas frente al mar en la ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/oAgPpYnjXBLkPex38",
    direccion: "Sector de Coco Pando, con acceso a la calle 8. ",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 193800,
    precioLempiras: 4782984,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T2/1.jpeg", "/T2/2.jpeg", "/T2/3.jpeg"],
    varas2: 119600,
    metros2: 83569,
  },
  {
    codigo: "T46",
    nombre: "Terreno en valle de angeles",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/TNPdS8HWXxsxbFx68",
    direccion: "Valle de Angeles Aldea las Cabañas, el mirador",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 166733.75,
    precioLempiras: 4114989,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T46/1.jpeg", "/T46/2.jpeg"],
    varas2: 3048.14,
    metros2: 2130,
  },
  {
    codigo: "T17",
    nombre: "Terreno Ceiba HN",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/cKkQTk6RLbLtnXEs5",
    direccion: "La Ceiba, en el Naranjal",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 215194.49,
    precioLempiras: 5311000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T17/1.jpeg", "/T17/2.jpeg", "/T17/3.jpeg", "/T17/4.jpeg"],
    varas2: 1305,
    metros2: 911.9,
  },
  {
    codigo: "T14",
    nombre: "Terreno en venta la ceiba hn",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/aMDZd1E1gBhZMpDu7",
    direccion: "Colonia D Antoni",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 14586.71,
    precioLempiras: 360000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T14/1.jpeg", "/T14/2.jpeg"],
    varas2: 286.2,
    metros2: 200,
  },
  {
    codigo: "T12",
    nombre: "Terreno de 2 Manzanas en Ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/QiMfiX1ViT3BZsnt5",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 344408.43,
    precioLempiras: 8500000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T12/1.jpeg", "/T12/2.jpeg", "/T12/3.jpeg"],
    varas2: NaN,
    metros2: NaN,
  },
  {
    codigo: "T47",
    nombre: "Terreno en barrio el centro",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/E34hnTJ4V15gX25N7",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 38492.71,
    precioLempiras: 950000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T47/1.jpeg", "/T47/2.jpeg", "/T47/3.jpeg", "/T47/4.jpeg"],
    varas2: 299,
    metros2: 209,
  },
  {
    codigo: "T48",
    nombre: "Terreno a orilla de playa, se ve enfrente cayos cochinos",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/qcgrGWMASuYY8qeB9",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 300000,
    precioLempiras: 7404000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/T48/1.jpeg",
      "/T48/2.jpeg",
      "/T48/3.jpeg",
      "/T48/4.jpeg",
      "/T48/5.jpeg",
      "/T48/6.jpeg",
      "/T48/7.jpeg",
    ],
    varas2: 10343.78,
    metros2: 7227,
  },
  {
    codigo: "T49",
    nombre: "Terreno 9.55 manzanas Roma La Ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/amfRDU9MFpGWYdEZ9",
    direccion: "La Ceiba",
    compartidaODirecta: "Compartida",
    ciudad: "La Ceiba",
    precioDolares: 1094003.24,
    precioLempiras: 27000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/T49/1.jpeg",
      "/T49/2.jpeg",
      "/T49/3.jpeg",
      "/T49/4.jpeg",
      "/T49/5.jpeg",
      "/T49/6.jpeg",
    ],
    varas2: NaN,
    metros2: NaN,
  },
  {
    codigo: "T50",
    nombre: "Terreno en residencial monte real del bosque",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/amfRDU9MFpGWYdEZ9",
    direccion: "La Ceiba",
    compartidaODirecta: "Compartida",
    ciudad: "La Ceiba",
    precioDolares: 28363.05,
    precioLempiras: 700000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/T50/1.jpeg",
      "/T50/2.jpeg",
      "/T50/3.jpeg",
      "/T50/4.jpeg",
      "/T50/5.jpeg",
      "/T50/6.jpeg",
      "/T50/7.jpeg",
      "/T50/8.jpeg",
    ],
    varas2: 428.6,
    metros2: 298.82,
  },
  {
    codigo: "T51",
    nombre: "Terrenos cerca del mar en la ensenada",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/EcLfRx5Qovfgkg6f7",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 44570.5,
    precioLempiras: 1100000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T51/1.jpeg"],
    varas2: 393.42,
    metros2: 275,
  },
  {
    codigo: "T39",
    nombre: "Terreno lomas del Mayab",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/DezApyngiXsHsP3YA",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 418320,
    precioLempiras: 10324137.6,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T39/1.jpeg", "/T39/2.jpeg", "/T39/3.jpeg"],
    varas2: 1494,
    metros2: 1044,
  },
  {
    codigo: "T41",
    nombre: "Terreno de 6000 v en el hatillo",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/7zxstj2xoxtjnzzC6",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 301458.67,
    precioLempiras: 7440000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T41/1.jpeg", "/T41/2.jpeg", "/T41/3.jpeg"],
    varas2: 6000,
    metros2: 4192,
  },
  {
    codigo: "T42",
    nombre: "Terreno en Mateo",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/Si3AhY3nkTxjkRZWA",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 269448.95,
    precioLempiras: 6650000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T42/1.jpeg"],
    varas2: 10222,
    metros2: 8541.76,
  },
  {
    codigo: "T53",
    nombre: "40 Manzanas en laguna del cacao",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/odB1ECSmWanVw97GA",
    direccion: "Jutiapa",
    compartidaODirecta: "Directa",
    ciudad: "Atlantida",
    precioDolares: 648298.22,
    precioLempiras: 16000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T53/1.jpeg", "/T53/2.jpeg", "/T53/3.jpeg", "/T53/4.jpeg"],
    varas2: 478400,
    metros2: 334276,
  },
  {
    codigo: "T54",
    nombre: "13 Manzanas en Valle de Angeles",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/3gUxmJAn1orK1Tf18",
    direccion: "Tegucigalpa",
    compartidaODirecta: "",
    ciudad: "Francisco Morazan",
    precioDolares: 62668.11,
    precioLempiras: 1546649,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T54/1.jpeg", "/T54/2.jpeg", "/T54/3.jpeg"],
    varas2: 155480,
    metros2: 108640,
  },
  {
    codigo: "T55",
    nombre: "Terreno Olanchito Yoro",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/35kLkmBmZQKXk9ko7",
    direccion: "Yoro",
    compartidaODirecta: "",
    ciudad: "Yoro",
    precioDolares: 153970.83,
    precioLempiras: 3800000,
    oferta: "Venta",
    observaciones: "",
    imagenes: [
      "/T55/1.jpeg",
      "/T55/2.jpeg",
      "/T55/3.jpeg",
      "/T55/4.jpeg",
      "/T55/5.jpeg",
    ],
    varas2: 525.64,
    metros2: 367.3,
  },
  {
    codigo: "T52",
    nombre: "7 manzanas en Granadita, La Ceiba",
    tipoDePropiedad: "Terreno",
    ubicacionGoogleMaps: "https://maps.app.goo.gl/EVVmA4BtDFTD9ZhE6",
    direccion: "La Ceiba",
    compartidaODirecta: "Directa",
    ciudad: "La Ceiba",
    precioDolares: 769854.13,
    precioLempiras: 19000000,
    oferta: "Venta",
    observaciones: "",
    imagenes: ["/T52/1.jpeg", "/T52/2.jpeg"],
    varas2: 83720,
    metros2: 58498,
  },
];
